openapi: 3.0.0
info:
  title: Microsoft Defender for Cloud
  description: Microsoft Defender for Cloud API
  version: 2025-01-01-preview
servers:
  - url: https://management.azure.com
paths:
  /subscriptions/{SUBSCRIPTION_ID}/providers/Microsoft.Security/assessmentMetadata/{assessment_id}?api-version=2020-01-01:
    get:
      operationId: AssessmentMetadata_Get
      summary: Get assessment metadata
      description: Get assessment metadata
      parameters:
        - name: SUBSCRIPTION_ID
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
        - name: assessment_id
          in: path
          description: Assessment ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /subscriptions/{SUBSCRIPTION_ID}/providers/Microsoft.Security/assessments?api-version=2021-06-01:
    get:
      operationId: Scanned Assessments
      summary: Get security assessments on all your scanned resources inside a scope
      description: Get MDC assessents
      parameters:
        - name: SUBSCRIPTION_ID
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                nextLink: null
                value: 
                  - id: "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1/providers/Microsoft.Security/assessments/21300918-b2e3-0346-785f-c77ff57d243b"
                    name: "21300918-b2e3-0346-785f-c77ff57d243b"
                    type: "Microsoft.Security/assessments"
                    properties: 
                      resourceDetails: 
                        source: "Azure"
                        id: "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1"
                      displayName: "Install endpoint protection solution on virtual machine scale sets"
                      status: 
                        code: "Healthy"
                        statusChangeDate: "2021-04-12T09:07:18.6759138Z"
                        firstEvaluationDate: "2021-04-12T09:07:18.6759138Z"
                  - id: "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.Compute/virtualMachineScaleSets/vmss2/providers/Microsoft.Security/assessments/21300918-b2e3-0346-785f-c77ff57d243b"
                    name: "21300918-b2e3-0346-785f-c77ff57d243b"
                    type: "Microsoft.Security/assessments"
                    properties: 
                      resourceDetails: 
                        source: "Azure"
                        id: "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.Compute/virtualMachineScaleSets/vmss2"
                      displayName: "Install endpoint protection solution on virtual machine scale sets"
                      status: 
                        code: "NotApplicable"
                        cause: "OffByPolicy"
                        description: "The effective policy for the assessment was evaluated to off - use Microsoft.Authorization/policyAssignments to turn this assessment on"
                        statusChangeDate: "2021-04-12T09:07:18.6759138Z"
                        firstEvaluationDate: "2021-04-12T09:07:18.6759138Z"
                      additionalData: 
                        linkedWorkspaceId: "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myLaWorkspace"
                        
